import { Room, Testimonial, SpaTreatment, MenuCategory, Experience, FAQ } from '@/types';

export const rooms: Room[] = [
  {
    id: 'standard-room',
    name: 'Standard Room',
    nameFr: 'Chambre Standard',
    namePt: 'Quarto Standard',
    description: 'A welcoming retreat with comfortable furnishings, air conditioning, and all the essentials for a pleasant stay in the heart of Gombe.',
    descriptionFr: 'Un accueil chaleureux avec un mobilier confortable, la climatisation et tout le nécessaire pour un séjour agréable au cœur de la Gombe.',
    descriptionPt: 'Um retiro acolhedor com mobiliário confortável, ar-condicionado e tudo o necessário para uma estadia agradável no coração de Gombe.',
    price: 92,
    currency: 'USD',
    size: 28,
    maxGuests: 2,
    bedType: 'Queen Bed',
    amenities: ['Free WiFi', 'Air Conditioning', 'Smart TV 42"', 'Minibar', 'Safe', 'Desk', 'Blackout Curtains', 'Daily Housekeeping'],
    images: ['/images/rooms/standard-1.jpg', '/images/rooms/standard-2.jpg'],
    featured: false,
    slug: 'standard-room',
  },
  {
    id: 'deluxe-room',
    name: 'Deluxe Room',
    nameFr: 'Chambre Deluxe',
    namePt: 'Quarto Deluxe',
    description: 'Elegantly appointed with contemporary African design, featuring a separate sitting area, premium linens, and city or pool views.',
    descriptionFr: 'Élégamment décoré avec un design africain contemporain, avec un salon séparé, de la literie premium et des vues sur la ville ou la piscine.',
    descriptionPt: 'Elegantemente decorado com design africano contemporâneo, com sala de estar separada, lençóis premium e vista para a cidade ou piscina.',
    price: 122,
    currency: 'USD',
    size: 35,
    maxGuests: 2,
    bedType: 'King Bed',
    amenities: ['Free WiFi', 'Air Conditioning', 'Smart TV 42"', 'Minibar', 'Safe', 'Sitting Area', 'Select Comfort Mattress', 'Premium Toiletries'],
    images: ['/images/rooms/deluxe-1.jpg', '/images/rooms/deluxe-2.jpg'],
    featured: true,
    slug: 'deluxe-room',
  },
  {
    id: 'executive-suite',
    name: 'Executive Suite',
    nameFr: 'Suite Exécutive',
    namePt: 'Suíte Executiva',
    description: 'Spacious suite designed for the discerning traveler, featuring a private study, work area, and premium amenities for business and leisure.',
    descriptionFr: 'Suite spacieuse conçue pour le voyageur exigeant, avec un bureau privé, un espace de travail et des équipements premium pour les affaires et les loisirs.',
    descriptionPt: 'Suíte espaçosa projetada para o viajante exigente, com estudo privado, área de trabalho e comodidades premium para negócios e lazer.',
    price: 166,
    currency: 'USD',
    size: 52,
    maxGuests: 3,
    bedType: 'King Bed + Sofa',
    amenities: ['Free WiFi', 'Air Conditioning', 'Smart TV 42"', 'Minibar', 'Safe', 'Private Study', 'Separate Living Area', 'Premium Butler', 'Bose Sound'],
    images: ['/images/rooms/executive-1.jpg', '/images/rooms/junior-suite-1.jpg'],
    featured: true,
    slug: 'executive-suite',
  },
  {
    id: 'junior-suite',
    name: 'Junior Suite',
    nameFr: 'Suite Junior',
    namePt: 'Suíte Junior',
    description: 'An open-plan retreat combining sleeping and living areas, with curated art pieces, a wardrobe, and views of the garden or city.',
    descriptionFr: 'Un retrait ouvert combinant espaces de vie et de couchage, avec des œuvres d\'art, une penderie et des vues sur le jardin ou la ville.',
    descriptionPt: 'Um retiro aberto combinando áreas de dormir e estar, com peças de arte, armário e vistas para o jardim ou a cidade.',
    price: 145,
    currency: 'USD',
    size: 42,
    maxGuests: 2,
    bedType: 'King Bed',
    amenities: ['Free WiFi', 'Air Conditioning', 'Smart TV 42"', 'Minibar', 'Safe', 'Living Area', 'Wardrobe', 'Tea/Coffee Maker', 'Ironing Facilities'],
    images: ['/images/rooms/junior-suite-1.jpg', '/images/rooms/deluxe-1.jpg'],
    featured: false,
    slug: 'junior-suite',
  },
];

export const testimonials: Testimonial[] = [
  {
    id: '1',
    name: 'Marie-Claire Dubois',
    country: 'France',
    rating: 5,
    text: 'An absolutely magical experience. The attention to detail is unmatched. Every moment felt like a scene from a luxury film.',
    textFr: 'Une expérience absolument magique. L\'attention aux détails est inégalée. Chaque moment ressemblait à une scène de film de luxe.',
    textPt: 'Uma experiência absolutamente mágica. A atenção aos detalhes é incomparável. Cada momento parecia uma cena de um filme de luxo.',
    date: '2024-01-15',
    avatar: '/images/testimonials/marie-claire.jpg',
  },
  {
    id: '2',
    name: 'James Henderson',
    country: 'United Kingdom',
    rating: 5,
    text: 'Belle Vie redefines what luxury means in Africa. The presidential suite is breathtaking. A true masterpiece of hospitality.',
    textFr: 'Belle Vie redéfinit ce que le luxe signifie en Afrique. La suite présidentielle est à couper le souffle. Un véritable chef-d\'œuvre.',
    textPt: 'Belle Vie redefine o que o luxo significa na África. A suíte presidencial é deslumbrante. Uma verdadeira obra-prima.',
    date: '2024-02-20',
    avatar: '/images/testimonials/james.jpg',
  },
  {
    id: '3',
    name: 'Aïcha Kabila',
    country: 'DR Congo',
    rating: 5,
    text: 'Enfin un hôtel qui représente la vraie élégance congolaise. Le service est impeccable, l\'ambiance est envoûtante.',
    textFr: 'Enfin un hôtel qui représente la vraie élégance congolaise. Le service est impeccable, l\'ambiance est envoûtante.',
    textPt: 'Finalmente um hotel que representa a verdadeira elegância congolesa. O serviço é impecável, a atmosfera é cativante.',
    date: '2024-03-10',
    avatar: '/images/testimonials/aicha.jpg',
  },
  {
    id: '4',
    name: 'Takeshi Yamamoto',
    country: 'Japan',
    rating: 5,
    text: 'The perfect blend of African warmth and Japanese attention to detail. The spa treatments are world-class.',
    textFr: 'Le mélange parfait de chaleur africaine et d\'attention japonaise aux détails. Les soins du spa sont de classe mondiale.',
    textPt: 'A mistura perfeita de calor africano e atenção japonesa aos detalhes. Os tratamentos do spa são de classe mundial.',
    date: '2024-04-05',
    avatar: '/images/testimonials/takeshi.jpg',
  },
  {
    id: '5',
    name: 'Sofia Martinez',
    country: 'Spain',
    rating: 5,
    text: 'From the moment you enter, you feel transported to another world. The restaurant alone is worth the visit. Magnificent.',
    textFr: 'Dès que vous entrez, vous vous sentez transporté dans un autre monde. Le restaurant seul vaut le voyage. Magnifique.',
    textPt: 'Desde o momento em que entra, sente-se transportado para outro mundo. O restaurante sozinho vale a visita. Magnífico.',
    date: '2024-05-18',
    avatar: '/images/testimonials/sofia.jpg',
  },
];

export const spaTreatments: SpaTreatment[] = [
  {
    id: 'congolese-stone',
    name: 'Congolese Hot Stone Massage',
    nameFr: 'Massage aux Pierres Chaudes Congolaises',
    namePt: 'Massagem com Pedras Quentes Congolesas',
    description: 'Ancient healing tradition meets modern luxury. Warm volcanic stones melt away tension while aromatic oils nourish the skin.',
    descriptionFr: 'La tradition de guérison ancienne rencontre le luxe moderne. Des pierres volcaniques chaudes font fondre les tensions.',
    descriptionPt: 'A antiga tradição de cura encontra o luxo moderno. Pedras vulcânicas quentes derretem a tensão.',
    duration: 90,
    price: 180,
    category: 'Massage',
    image: '/images/spa/stone-massage.jpg',
  },
  {
    id: 'diamond-facial',
    name: 'Diamond Radiance Facial',
    nameFr: 'Soin Visage Éclat Diamant',
    namePt: 'Facial Brilho de Diamante',
    description: 'Indulge in our signature facial featuring diamond-infused serums that leave your skin luminous and youthful.',
    descriptionFr: 'Offrez-vous notre soin visage signature avec des sérums à base de diamant pour une peau lumineuse et jeune.',
    descriptionPt: 'Indulge em nosso facial exclusivo com sérum infusionado com diamante que deixa sua pele luminosa e jovem.',
    duration: 75,
    price: 250,
    category: 'Facial',
    image: '/images/spa/diamond-facial.jpg',
  },
  {
    id: 'river-ritual',
    name: 'Congo River Ritual',
    nameFr: 'Rituel du Fleuve Congo',
    namePt: 'Ritual do Rio Congo',
    description: 'A holistic body treatment inspired by the mighty Congo River. Exfoliation, wrap, and massage in perfect harmony.',
    descriptionFr: 'Un soin corporel holistique inspiré du puissant fleuve Congo. Gommage, enveloppement et massage en parfaite harmonie.',
    descriptionPt: 'Um tratamento corporal holístico inspirado no poderoso Rio Congo. Esfoliação, envolvimento e massagem em perfeita harmonia.',
    duration: 120,
    price: 320,
    category: 'Body Treatment',
    image: '/images/spa/river-ritual.jpg',
  },
  {
    id: 'bamboo-balance',
    name: 'Bamboo Balance Therapy',
    nameFr: 'Thérapie Équilibre Bambou',
    namePt: 'Terapia Equilíbrio Bambu',
    description: 'Eastern wisdom meets African soul. Bamboo sticks are used to release deep-seated tension and restore energy flow.',
    descriptionFr: 'La sagesse orientale rencontre l\'âme africaine. Des bâtons de bambou sont utilisés pour libérer les tensions profondes.',
    descriptionPt: 'A sabedoria oriental encontra a alma africana. Grãos de bambu são usados para liberar tensões profundas.',
    duration: 60,
    price: 140,
    category: 'Massage',
    image: '/images/spa/bamboo.jpg',
  },
];

export const restaurantMenu: MenuCategory[] = [
  {
    id: 'starters',
    name: 'Starters',
    nameFr: 'Entrées',
    namePt: 'Entradas',
    items: [
      {
        id: 'tuna-tartare',
        name: 'Tuna Tartare',
        nameFr: 'Tartare de Thon',
        namePt: 'Tartare de Atum',
        description: 'Fresh yellowfin tuna, avocado, sesame, ponzu',
        descriptionFr: 'Thon frais, avocat, sésame, ponzu',
        descriptionPt: 'Atum fresco, abacate, gergelim, ponzu',
        price: 28,
        dietary: ['GF'],
        image: '/images/restaurant/tuna-tartare.jpg',
      },
      {
        id: 'congolese-soup',
        name: 'Madesu Soup',
        nameFr: 'Soupe Madesu',
        namePt: 'Sopa Madesu',
        description: 'Traditional Congolese bean soup with aromatic spices',
        descriptionFr: 'Soupe traditionnelle aux haricots congolais aux épices aromatiques',
        descriptionPt: 'Sopa tradicional de feijão congolesa com especiarias aromáticas',
        price: 18,
        dietary: ['VG', 'GF'],
        image: '/images/restaurant/madesu.jpg',
      },
      {
        id: 'foie-gras',
        name: 'Foie Gras Terrine',
        nameFr: 'Terrine de Foie Gras',
        namePt: 'Terrine de Foie Gras',
        description: 'Duck foie gras, brioche, fig compote, port reduction',
        descriptionFr: 'Foie gras de canard, brioche, compotée de figues, réduction de porto',
        descriptionPt: 'Foie gras de pato, briose, compota de figo, redução de porto',
        price: 38,
        dietary: [],
        image: '/images/restaurant/foie-gras.jpg',
      },
    ],
  },
  {
    id: 'mains',
    name: 'Main Courses',
    nameFr: 'Plats Principaux',
    namePt: 'Pratos Principais',
    items: [
      {
        id: 'wagyu-steak',
        name: 'Wagyu Beef Tenderloin',
        nameFr: 'Filet de Boeuf Wagyu',
        namePt: 'Filé de Wagyu',
        description: 'A5 Wagyu, truffle jus, roasted vegetables, potato mousseline',
        descriptionFr: 'Wagyu A5, jus de truffe, légumes rôtis, mousseline de pommes de terre',
        descriptionPt: 'Wagyu A5, molho de trufa, legumes assados, mousseline de batata',
        price: 85,
        dietary: ['GF'],
        image: '/images/restaurant/wagyu.jpg',
      },
      {
        id: 'lobster',
        name: 'Congo Lobster Thermidor',
        nameFr: 'Homard du Congo Thermidor',
        namePt: 'Lagosta do Congo Thermidor',
        description: 'Freshwater lobster, gruyère crust, saffron rice',
        descriptionFr: 'Homard d\'eau douce, croûte de gruyère, riz au safran',
        descriptionPt: 'Lagosta de água doce, crosta de gruyère, arroz com açafrão',
        price: 72,
        dietary: ['GF'],
        image: '/images/restaurant/lobster.jpg',
      },
      {
        id: 'ndole',
        name: 'Refined Ndolé',
        nameFr: 'Ndolé Raffiné',
        namePt: 'Ndolé Refinado',
        description: 'Bitter leaves, shrimp, peanuts, plantain chips',
        descriptionFr: 'Feuilles amères, crevettes, arachides, chips de plantain',
        descriptionPt: 'Folhas amargas, camarão, amendoim, chips de banana-da-terra',
        price: 42,
        dietary: ['GF'],
        image: '/images/restaurant/ndole.jpg',
      },
    ],
  },
  {
    id: 'desserts',
    name: 'Desserts',
    nameFr: 'Desserts',
    namePt: 'Sobremesas',
    items: [
      {
        id: 'chocolate-fondant',
        name: 'Chocolate Fondant',
        nameFr: 'Fondant au Chocolat',
        namePt: 'Bombom de Chocolate',
        description: 'Valrhona dark chocolate, vanilla ice cream, gold leaf',
        descriptionFr: 'Chocolat noir Valrhone, glace vanille, feuille d\'or',
        descriptionPt: 'Chocolate Valrhona amargo, sorvete de baunilha, folha de ouro',
        price: 22,
        dietary: ['GF'],
        image: '/images/restaurant/chocolate.jpg',
      },
      {
        id: 'tropical-parfait',
        name: 'Tropical Paradise Parfait',
        nameFr: 'Parfait Paradis Tropical',
        namePt: 'Parfait Paraíso Tropical',
        description: 'Mango, passion fruit, coconut, vanilla bean',
        descriptionFr: 'Mangue, fruit de la passion, noix de coco, gousse de vanille',
        descriptionPt: 'Manga, maracujá, coco, baunilha',
        price: 18,
        dietary: ['VG', 'GF'],
        image: '/images/restaurant/parfait.jpg',
      },
    ],
  },
];

export const experiences: Experience[] = [
  {
    id: 'airport-transfer',
    name: 'VIP Airport Transfer',
    nameFr: 'Transfert VIP Aéroport',
    namePt: 'Transfer VIP Aeroporto',
    description: 'Arrive in style with our luxury fleet. Champagne welcome, personal escort through the airport.',
    descriptionFr: 'Arrivez en toute élégance avec notre flotte de luxe. Accueil champagne, escorte personnelle à l\'aéroport.',
    descriptionPt: 'Chegue em estilo com nossa frota de luxo. Boas-vindas com champanhe, escolta pessoal no aeroporto.',
    price: 150,
    duration: '1-2 hours',
    image: '/images/experiences/transfer.jpg',
  },
  {
    id: 'city-tour',
    name: 'Kinshasa Heritage Tour',
    nameFr: 'Tour du Patrimoine de Kinshasa',
    namePt: 'Tour do Patrimônio de Kinshasa',
    description: 'Discover the soul of Kinshasa. From the National Museum to the vibrant markets, experience the real Congo.',
    descriptionFr: 'Découvrez l\'âme de Kinshasa. Du Musée National aux marchés vibrants, vivez le vrai Congo.',
    descriptionPt: 'Descubra a alma de Kinshasa. Do Museu Nacional aos mercados vibrantes, experimente o verdadeiro Congo.',
    price: 200,
    duration: '4-6 hours',
    image: '/images/experiences/city-tour.jpg',
  },
  {
    id: 'safari',
    name: 'Okapi Sanctuary Safari',
    nameFr: 'Safari Sanctuaire des Okapis',
    namePt: 'Safari Santuário dos Okapis',
    description: 'Journey to see the elusive okapi in its natural habitat. A once-in-a-lifetime wildlife encounter.',
    descriptionFr: 'Voyagez pour voir l\'élusif okapi dans son habitat naturel. Une rencontre avec la faune unique en son genre.',
    descriptionPt: 'Viaje para ver o esquivo okapi em seu habitat natural. Um encontro com a vida selvagem único.',
    price: 500,
    duration: 'Full Day',
    image: '/images/experiences/safari.jpg',
  },
  {
    id: 'sunset-cruise',
    name: 'Congo River Sunset Cruise',
    nameFr: 'Croisière au Coucher du Soleil sur le Congo',
    namePt: 'Cruzeiro do Pôr do Sol no Rio Congo',
    description: 'Sail into the African sunset aboard our luxury yacht. Champagne, canapés, and live music.',
    descriptionFr: 'Naviguez vers le coucher du soleil africain à bord de notre yacht de luxe. Champagne, canapés et musique live.',
    descriptionPt: 'Navegue ao pôr do sol africano a bordo de nosso iate de luxo. Champanhe, canapés e música ao vivo.',
    price: 300,
    duration: '3 hours',
    image: '/images/experiences/sunset-cruise.jpg',
  },
  {
    id: 'golf',
    name: 'Golf at Kinshasa Golf Club',
    nameFr: 'Golf au Kinshasa Golf Club',
    namePt: 'Golfe no Kinshasa Golf Club',
    description: 'Tee off at the most prestigious golf course in Central Africa. Club rental and pro lessons available.',
    descriptionFr: 'Jouez au golf sur le terrain le plus prestigieux d\'Afrique centrale. Location de clubs et cours disponibles.',
    descriptionPt: 'Jogue no campo de golfe mais prestigiado da África Central. Aluguel de tacos e aulas disponíveis.',
    price: 180,
    duration: '4 hours',
    image: '/images/experiences/golf.jpg',
  },
  {
    id: 'cooking-class',
    name: 'Congolese Cooking Masterclass',
    nameFr: 'Cours de Cuisine Congolaise',
    namePt: 'Aula Mestre de Culinária Congolesa',
    description: 'Learn the secrets of Congolese cuisine from our executive chef. Includes market tour and tasting.',
    descriptionFr: 'Apprenez les secrets de la cuisine congolaise de notre chef exécutif. Inclut visite du marché et dégustation.',
    descriptionPt: 'Aprenda os segredos da culinária congolesa com nosso chef executivo. Inclui visita ao mercado e degustação.',
    price: 120,
    duration: '3 hours',
    image: '/images/experiences/cooking.jpg',
  },
];

export const faqs: FAQ[] = [
  {
    id: 'check-in',
    question: 'What are the check-in and check-out times?',
    questionFr: 'Quelles sont les heures d\'arrivée et de départ?',
    questionPt: 'Quais são os horários de check-in e check-out?',
    answer: 'Check-in is at 3:00 PM and check-out is at 11:00 AM. Early check-in and late check-out are available upon request, subject to availability.',
    answerFr: 'L\'arrivée est à 15h00 et le départ à 11h00. L\'arrivée anticipée et le départ tardif sont disponibles sur demande, sous réserve de disponibilité.',
    answerPt: 'O check-in é às 15h00 e o check-out é às 11h00. Check-in antecipado e check-out tardio estão disponíveis mediante solicitação, sujeito a disponibilidade.',
  },
  {
    id: 'wifi',
    question: 'Is WiFi complimentary?',
    questionFr: 'Le WiFi est-il gratuit?',
    questionPt: 'O WiFi é gratuito?',
    answer: 'Yes, high-speed WiFi is complimentary throughout the hotel, including all rooms, suites, restaurants, and public areas.',
    answerFr: 'Oui, le WiFi haut débit est gratuit dans tout l\'hôtel, y compris toutes les chambres, suites, restaurants et espaces publics.',
    answerPt: 'Sim, WiFi de alta velocidade é gratuito em todo o hotel, incluindo todos os quartos, suítes, restaurantes e áreas públicas.',
  },
  {
    id: 'airport-shuttle',
    question: 'Do you offer airport transfers?',
    questionFr: 'Proposez-vous des transferts aéroport?',
    questionPt: 'Vocês oferecem transfer do aeroporto?',
    answer: 'Yes, we offer complimentary airport transfers for suite guests. For all other room types, our luxury fleet is available at preferential rates.',
    answerFr: 'Oui, nous offrons des transferts aéroport gratuits pour les clients en suite. Pour les autres types de chambres, notre flotte de luxe est disponible à des tarifs préférentiels.',
    answerPt: 'Sim, oferecemos transfer gratuito do aeroporto para hóspedes em suíte. Para todos os outros tipos de quarto, nossa frota de luxo está disponível em tarifas preferenciais.',
  },
  {
    id: 'dining',
    question: 'How many restaurants does the hotel have?',
    questionFr: 'Combien de restaurants l\'hôtel a-t-il?',
    questionPt: 'Quantos restaurantes o hotel tem?',
    answer: 'Belle Vie Hotel features three distinct dining experiences: Le Jardin (French-African fusion), The Terrace (all-day dining), and our intimate Private Dining room for exclusive chef\'s table experiences.',
    answerFr: 'Le Belle Vie Hotel propose trois expériences culinaires distinctes: Le Jardin (fusion franco-africaine), The Terrace (restauration toute la journée) et notre salle à manger privée intime.',
    answerPt: 'O Belle Vie Hotel oferece três experiências gastronômicas distintas: Le Jardin (fusão franco-africana), The Terrace (restaurante durante todo o dia) e nossa sala de jantar íntima.',
  },
];

export const poolInfo = {
  name: 'Infinity Pool',
  nameFr: 'Piscine à Débordement',
  namePt: 'Piscina Infinita',
  description: 'Our stunning infinity pool seems to merge with the Kinshasa skyline. Heated year-round, with dedicated poolside service.',
  descriptionFr: 'Notre magnifique piscine à débordement semble se fondre dans la ligne d\'horizon de Kinshasa. Chauffée toute l\'année, avec service dédié.',
  descriptionPt: 'Nossa deslumbrante piscina infinita parece se fundir com o horizonte de Kinshasa. Aquecida o ano todo, com serviço dedicado.',
  hours: '6:00 AM - 10:00 PM',
  features: ['Heated Pool', 'Sun Loungers', 'Poolside Bar', 'Private Cabanas', 'Towel Service', 'UV Purification'],
};

export const gymInfo = {
  name: 'Fitness Center',
  nameFr: 'Salle de Sport',
  namePt: 'Academia',
  description: 'State-of-the-art Technogym equipment, personal trainers, and a dedicated yoga studio.',
  descriptionFr: 'Équipements Technogym de pointe, entraîneurs personnels et studio de yoga dédié.',
  descriptionPt: 'Equipamentos Technogym de última geração, treinadores pessoais e estúdio de yoga dedicado.',
  hours: '24/7',
  features: ['Technogym Equipment', 'Personal Training', 'Yoga Studio', 'Steam Room', 'Sauna', 'Hydration Station'],
};

export const conferenceInfo = {
  name: 'Events & Conferences',
  nameFr: 'Événements & Conférences',
  namePt: 'Eventos & Conferências',
  description: 'From intimate board meetings to grand galas, our versatile spaces accommodate 10 to 500 guests.',
  descriptionFr: 'Des réunions de conseil intimes aux grands galas, nos espaces polyvalents accueillent 10 à 500 invités.',
  descriptionPt: 'De reuniões íntimas do conselho a galas grandiosas, nossos espaços versáteis acomodam 10 a 500 convidados.',
  venues: [
    { name: 'Congo Ballroom', capacity: 500, size: '800 sqm' },
    { name: 'Gombe Boardroom', capacity: 20, size: '60 sqm' },
    { name: 'Sunset Terrace', capacity: 150, size: '400 sqm' },
    { name: 'Garden Pavilion', capacity: 200, size: '500 sqm' },
  ],
};