export const siteConfig = {
  name: 'Belle Vie Hotel',
  description: 'A luxury hotel in the heart of Kinshasa, DR Congo. Where luxury meets serenity.',
  url: 'https://bellevuehotel.com',
  ogImage: '/images/og-image.jpg',
  creator: 'Belle Vie Hotel',
  keywords: [
    'luxury hotel',
    'Kinshasa hotel',
    'DR Congo hotel',
    'five star hotel',
    'Gombe hotel',
    'boutique hotel',
    'luxury accommodation',
    'Kinshasa luxury',
    'hotel booking',
    'business hotel',
    'conference hotel',
    'spa hotel',
    'restaurant hotel',
    'wedding venue',
    'corporate events',
  ],
  contact: {
    address: '16 Avenue Tombalbaye, Gombe, Kinshasa, Democratic Republic of the Congo',
    phone: '+243 976 050 000',
    phoneReservations: '+243 815 443 636',
    email: 'reservation@belleviehotel.com',
    website: 'https://bellevuehotel.com',
  },
  social: {
    facebook: 'https://facebook.com/belleviehotel',
    instagram: 'https://instagram.com/belleviehotel',
    twitter: 'https://twitter.com/belleviehotel',
    linkedin: 'https://linkedin.com/company/belleviehotel',
    tripadvisor: 'https://tripadvisor.com/belleviehotel',
    whatsapp: 'https://wa.me/243815443636',
  },
  defaultLocale: 'en',
  locales: ['en', 'fr', 'pt'],
  theme: {
    primaryColor: '#C9A84C',
    secondaryColor: '#1A1A1A',
    accentColor: '#E8C4C4',
    darkColor: '#0A0A0A',
    lightColor: '#F5F0E8',
  },
  hotel: {
    stars: 5,
    rooms: 120,
    floors: 8,
    yearEstablished: 2020,
    checkIn: '15:00',
    checkOut: '11:00',
    currency: 'USD',
  },
} as const;

export type SiteConfig = typeof siteConfig;